import type { ScheduleEventData, ScheduleResourceData } from '@mantine/schedule';

export const CON_DATES = {
  friday: '2026-08-07',
  saturday: '2026-08-08',
  sunday: '2026-08-09',
  monday: '2026-08-10', // departure day, no programming
} as const;

export const resources: ScheduleResourceData[] = [
  {
    id: 'entrance',
    label: 'Entrance',
  },
  {
    id: 'reception',
    label: 'Reception',
  },
  {
    id: 'bar',
    label: 'Bar',
  },
  {
    id: 'resturant',
    label: 'Restaurant',
  },
  {
    id: 'pool',
    label: 'Pool',
  },
  {
    id: 'shumba-hall',
    label: 'Shumba',
  },
  {
    id: 'small-boardroom',
    label: 'Small Boardroom',
  },
  {
    id: 'small-office',
    label: 'Con Ops',
  },
  {
    id: 'tlou-hall',
    label: 'Main Stage',
  },
  {
    id: 'kraal',
    label: 'Fursuit Lounge',
  },
  {
    id: 'nyathi',
    label: "Dealer's Den",
  },
  {
    id: 'gym',
    label: 'Gym',
  },
];

export const events: ScheduleEventData[] = [
  // ---------------------------------------------------------------- FRIDAY
  {
    id: 1,
    title: 'Registration',
    start: '2026-08-07 14:00:00',
    end: '2026-08-07 16:00:00',
    resourceId: 'entrance',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Entrance',
      description: 'The first steps to entering and being a part of the convention.',
    },
  },
  {
    id: 2,
    title: 'Registration',
    start: '2026-08-07 14:00:00',
    end: '2026-08-07 16:00:00',
    resourceId: 'reception',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Reception',
      description: 'The first steps to entering and being a part of the convention.',
    },
  },
  // {
  //   id: 3,
  //   title: 'Icebreaker Lunch',
  //   start: '2026-08-07 16:00:00',
  //   end: '2026-08-07 19:00:00',
  //   resourceId: 'bar',
  //   color: 'yellow',
  //   payload: {
  //     category: 'Meals',
  //     adult: false,
  //     day: 'Friday',
  //     room: 'Bar',
  //     description: 'Eat. Drink. Be merry, and maybe make a few new friends.',
  //   },
  // },
  {
    id: 4,
    title: 'Drinks / Socials',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Bar',
    },
  },
  {
    id: 5,
    title: 'Icebreaker Lunch',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Friday',
      room: 'Restaurant',
      description: 'Eat. Drink. Be merry, and maybe make a few new friends.',
    },
  },
  {
    id: 6,
    title: 'Icebreaker Lunch',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'pool',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Friday',
      room: 'Pool',
      description: 'Eat. Drink. Be merry, and maybe make a few new friends.',
    },
  },
  {
    id: 7,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-07 18:30:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 8,
    title: 'Opening Ceremonies',
    start: '2026-08-07 19:00:00',
    end: '2026-08-07 20:30:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
      host: 'Scratch',
      description:
        "The official announcement that SAFC 2026 has begun, and the who's who in the zoo.",
    },
  },
  {
    id: 9,
    title: 'Karaoke',
    start: '2026-08-07 20:30:00',
    end: '2026-08-07 22:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
      description: 'Sing, howl, meow, share your voice with the willing and unwilling alike.',
    },
  },
  {
    id: 10,
    title: 'AD Games',
    start: '2026-08-07 22:00:00',
    end: '2026-08-07 23:59:59',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Friday',
      room: 'Tlou Hall',
      host: 'Lyt & Romey',
      description: 'Bring out your inner kink and join in the adult festivities.',
    },
  },
  {
    id: 11,
    title: 'Fursuiting Availability',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 23:59:59',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Kraal',
    },
  },
  // {
  //   id: 14,
  //   title: 'Mystery Game: Bull Pen',
  //   start: '2026-08-07 20:30:00',
  //   end: '2026-08-07 21:00:00',
  //   resourceId: 'nyathi',
  //   color: 'blue',
  //   payload: {
  //     category: 'Panel / Activity',
  //     adult: false,
  //     day: 'Friday',
  //     room: 'Nyathi',
  //     host: 'Badgacat',
  //     description: 'The clues to the mystery are waiting to be found.',
  //   },
  // },
  {
    id: 15,
    title: 'Fursuiting Photo Op',
    start: '2026-08-08 20:30:00',
    end: '2026-08-08 23:00:00',
    resourceId: 'gym',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Gym',
      host: 'Kyra',
      description: 'Allocated, theme-friendly areas dedicated to fursuiting photos.',
    },
  },

  {
    id: 16,
    title: 'Fursuiting Photo Op',
    start: '2026-08-07 20:30:00',
    end: '2026-08-07 23:00:00',
    resourceId: 'gym',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Gym',
      host: 'Kyra',
      description: 'Allocated, theme-friendly areas dedicated to fursuiting photos.',
    },
  },
  {
    id: 13,
    title: 'Fursuiting Photo Op',
    start: '2026-08-09 20:30:00',
    end: '2026-08-09 23:00:00',
    resourceId: 'gym',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Gym',
      host: 'Kyra',
      description: 'Allocated, theme-friendly areas dedicated to fursuiting photos.',
    },
  },
  // -------------------------------------------------------------- SATURDAY
  {
    id: 17,
    title: 'Drinks / Socials',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Bar',
    },
  },
  {
    id: 18,
    title: 'Admin Brunch',
    start: '2026-08-08 09:00:00',
    end: '2026-08-08 10:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 19,
    title: 'Brunch',
    start: '2026-08-08 10:00:00',
    end: '2026-08-08 11:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 20,
    title: 'Admin Linner',
    start: '2026-08-08 16:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 21,
    title: 'Linner',
    start: '2026-08-08 17:00:00',
    end: '2026-08-08 18:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 22,
    title: 'Social & Gathering',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 18:00:00',
    resourceId: 'pool',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Pool',
    },
  },
  {
    id: 23,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-08 08:30:00',
    end: '2026-08-08 09:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 24,
    title: 'Paws To The Beat',
    start: '2026-08-08 09:00:00',
    end: '2026-08-08 10:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Kyuki',
      description: 'A collaborative dancercise class for all ages and skill levels.',
    },
  },
  {
    id: 25,
    title: 'Funger Games',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 12:00:00',
    resourceId: 'shumba-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Ender',
      description:
        "A game to see if the contestants have what it takes to be a furry. 2-4 players are chosen per game and the winner moves on to the next round, but players won't know who they'll be competing against or which game they'll play.",
    },
  },
  {
    id: 26,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-08 12:00:00',
    end: '2026-08-08 12:30:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 27,
    title: 'Life After Animation: From Industry Veteran to Avatar Creator',
    start: '2026-08-08 12:30:00',
    end: '2026-08-08 14:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Bowie',
      description:
        'The journey from 3D animation student, to animation and VFX industry veteran with 14 years of experience, to furry VTuber and avatar creator.',
    },
  },
  {
    id: 28,
    title: 'Furry Feud',
    start: '2026-08-08 16:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Raging Snep',
      description:
        "A light-hearted spin-off of Family Feud where participants guess the most popular furry and convention answers from audience surveys, culminating in a high-energy 'Fur the money' bonus round.",
    },
  },
  {
    id: 29,
    title: 'Pup-Play Photos',
    start: '2026-08-08 23:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Saturday',
      room: 'Shumba Hall',
      description:
        "Pups and owners can meet up and take photos, and be part of the dog show, even if you're a feline.",
    },
  },
  {
    id: 30,
    title: 'Blood On The Clocktower',
    start: '2026-08-08 14:00:00',
    end: '2026-08-08 16:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Boardroom',
      host: 'ARKA & Farvern',
      description:
        'A social deduction party game, very common at American fur cons. Good players versus evil players, who shall be the ones to succeed?',
    },
  },
  {
    id: 31,
    title: 'Blood On The Clocktower',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 20:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Boardroom',
      host: 'ARKA & Farvern',
      description:
        'A social deduction party game, very common at American fur cons. Good players versus evil players, who shall be the ones to succeed?',
    },
  },
  {
    id: 33,
    title: 'The Switch Switch',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 19:00:00',
    resourceId: 'small-office',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Office',
      host: 'Sudan Red',
      description:
        'Connoisseurs of the highest calibre unite to trial their palettes against the sophistication that is Switch.',
    },
  },
  {
    id: 34,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-08 19:00:00',
    end: '2026-08-08 19:30:00',
    resourceId: 'small-office',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Office',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 35,
    title: 'Fursuit 101',
    start: '2026-08-08 14:00:00',
    end: '2026-08-08 15:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
      host: 'Kiyo',
      description:
        "Lessons for wearing and caring for the most expensive portable carpet you'll ever own and wear.",
    },
  },
  {
    id: 36,
    title: 'Fursuit Games',
    start: '2026-08-08 15:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
      host: 'Kiyo',
      description: 'Have a fursuit? Borrowing a fursuit? Join the games, and join the FUN.',
    },
  },
  {
    id: 37,
    title: 'Rave',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 23:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
      host: 'DJs Coffeebuscuit, Rigel & Slushy',
      description:
        "Music soothes the wild beast... not this time! Join a group of wild animals dancing to their heart's content.",
    },
  },
  {
    id: 38,
    title: 'Fursuiting Availability',
    start: '2026-08-08 09:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Kraal',
    },
  },
  {
    id: 39,
    title: 'Dealers Den',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: false,
      day: 'Saturday',
      room: 'Nyathi',
      description:
        'Swag yourselves up to the nines. Buy that little something special for yourself. Go on, you deserve it.',
    },
  },
  {
    id: 40,
    title: 'Dealers Den AD',
    start: '2026-08-08 20:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: true,
      day: 'Saturday',
      room: 'Nyathi',
      description:
        "Santa gets you gifts for being good, so you'll have to get yourself all the naughty ones.",
    },
  },

  // ---------------------------------------------------------------- SUNDAY
  {
    id: 41,
    title: 'Drinks / Socials',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Bar',
    },
  },
  {
    id: 42,
    title: 'Admin Brunch',
    start: '2026-08-09 09:00:00',
    end: '2026-08-09 10:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 43,
    title: 'Brunch',
    start: '2026-08-09 10:00:00',
    end: '2026-08-09 11:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 44,
    title: 'Admin Linner',
    start: '2026-08-09 16:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 45,
    title: 'Linner',
    start: '2026-08-09 17:00:00',
    end: '2026-08-09 18:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 46,
    title: 'Social & Gathering',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 18:00:00',
    resourceId: 'pool',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Pool',
    },
  },
  {
    id: 47,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-09 08:30:00',
    end: '2026-08-09 09:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 48,
    title: 'Paws To The Beat',
    start: '2026-08-09 09:00:00',
    end: '2026-08-09 10:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      host: 'Kyuki',
      description: 'A collaborative dancercise class for all ages and skill levels.',
    },
  },
  {
    id: 49,
    title: "The Hybrid's Hybrid Art Challenge",
    start: '2026-08-09 15:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      host: 'Thabz and Judee',
      description:
        'An art competition to create a new hybrid character from animals we provide, in theme with the con, with a warm-up figure-drawing session.',
    },
  },
  {
    id: 50,
    title: 'Movies',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:59:59',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      description:
        'Snuggle up, make ready the snacks you snuck in, and get ready for some cinematic chill time.',
    },
  },
  {
    id: 51,
    title: 'Business & Taxes',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 12:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Kiyo/Yote',
      description:
        "The business of understanding your business, and let's throw in some tax for fun's sake.",
    },
  },
  {
    id: 52,
    title: 'Furry Business 101',
    start: '2026-08-09 12:00:00',
    end: '2026-08-09 13:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Blueberry',
      description:
        'How to run a business in the furry fandom: good practices and things to consider when owning furry-oriented businesses.',
    },
  },
  {
    id: 53,
    title: 'The South-African IT Landscape For Students & Jobseekers',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 14:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'CheddarByte',
      description:
        'An overview of the I.T. landscape in South Africa, with guidance and advice for new jobseekers and students, plus the different fields available under the I.T. umbrella.',
    },
  },
  {
    id: 55,
    title: 'So You Want To Run A Furry Con',
    start: '2026-08-09 14:30:00',
    end: '2026-08-09 15:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Kiyo, Scarlet Jack & Scratch',
      description:
        'Discussions around the administrative, financial and management challenges that come with running events in the local furry scene.',
    },
  },
  {
    // Relocated from Saturday: the timescape places Intro to Impact Play on SUNDAY, Small Boardroom.
    id: 32,
    title: 'Intro to Impact Play',
    start: '2026-08-09 23:00:00',
    end: '2026-08-09 23:59:59',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Rigel Badger',
      description:
        'Impact play in BDSM: what the draws are, what gear to use, and how to do it safely.',
    },
  },
  {
    id: 56,
    title: 'Mystery Game: Bull Pen',
    start: '2026-08-09 12:30:00',
    end: '2026-08-09 13:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Badgacat',
      description: 'The clues to the mystery are waiting to be found.',
    },
  },
  {
    id: 57,
    title: 'Fursuit Games',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 15:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Kiyo',
      description: 'Have a fursuit? Borrowing a fursuit? Join the games, and join the FUN.',
    },
  },
  {
    id: 58,
    title: 'Sudan Quiz',
    start: '2026-08-09 15:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Sudan Red',
      description:
        "A quiz that is both fun and challenging. Test your mettle against Sudan's iron will and keen questions.",
    },
  },
  {
    id: 59,
    title: 'SAFC Dance Competition',
    start: '2026-08-09 18:00:00',
    end: '2026-08-09 20:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      description:
        'Contestants dance like no one is watching, but we all shall be, judges and audience alike. Who has the moves? May the top dancer win!',
    },
  },
  {
    id: 60,
    title: 'Raffle',
    start: '2026-08-09 20:00:00',
    end: '2026-08-09 21:00:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Scratch',
      description:
        "The drawing of the donated items, all for charity. Alms and succour for this year's charity, Fallen Angels Pet Rescue.",
    },
  },
  {
    id: 61,
    title: 'Closing Ceremonies',
    start: '2026-08-09 21:00:00',
    end: '2026-08-09 22:00:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Scratch',
      description:
        'The official announcement that SAFC 2026 has come to an end, with thanks and notices, including the Mystery Game winner.',
    },
  },
  {
    id: 62,
    title: 'The Spice Is Right',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Raging Snep',
      description:
        'A spin-off of The Price Is Right with a spicy twist: contestants guess numbers closest to metrics from a famous furry art aggregation site, across rounds such as tag count, score count, closest without going over, and A vs B.',
    },
  },
  {
    id: 63,
    title: 'Fursuiting Availability',
    start: '2026-08-09 09:00:00',
    end: '2026-08-10 01:00:00',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Kraal',
    },
  },
  {
    id: 64,
    title: 'Dealers Den',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: false,
      day: 'Sunday',
      room: 'Nyathi',
      description:
        'Swag yourselves up to the nines. Buy that little something special for yourself. Go on, you deserve it.',
    },
  },
  {
    id: 65,
    title: 'Dealers Den AD',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:59:59',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: true,
      day: 'Sunday',
      room: 'Nyathi',
      description:
        "Santa gets you gifts for being good, so you'll have to get yourself all the naughty ones.",
    },
  },
];
