// safcon-schedule-data.ts
// Auto-generated from Event_Layout_SAFCON26.xlsx (SAFCON'26 — "Claws & Order: A Noir Mystery")
// Con dates: Fri 7 Aug – Mon 10 Aug 2026. Monday is a departure day (no sessions in the layout).
//
// Category colours (Mantine palette):
//   Headline (P) = grape · Featured (S) = orange · Panel / Activity (T) = blue
//   Drop-in (F) = teal · Dealers / Sales (M) = green · Meals (N) = yellow
//
// Each event's payload carries { category, adult, day }. `adult: true` = 18+ content.

import type { ScheduleEventData, ScheduleResourceData } from '@mantine/schedule';

export const CON_DATES = {
  friday: '2026-08-07',
  saturday: '2026-08-08',
  sunday: '2026-08-09',
  monday: '2026-08-10', // departure day, no programming
} as const;

export const resources: ScheduleResourceData[] = [
  {
    id: 'entrance',
    label: 'Entrance',
  },
  {
    id: 'reception',
    label: 'Reception',
  },
  {
    id: 'bar',
    label: 'Bar',
  },
  {
    id: 'resturant',
    label: 'Restaurant',
  },
  {
    id: 'pool',
    label: 'Pool',
  },
  {
    id: 'shumba-hall',
    label: 'Shumba Hall',
  },
  {
    id: 'small-boardroom',
    label: 'Small Boardroom',
  },
  {
    id: 'small-office',
    label: 'Small Office',
  },
  {
    id: 'tlou-hall',
    label: 'Tlou Hall',
  },
  {
    id: 'kraal',
    label: 'Kraal',
  },
  {
    id: 'nyathi',
    label: 'Nyathi',
  },
  {
    id: 'gym',
    label: 'Gym',
  },
];

export const events: ScheduleEventData[] = [
  {
    id: 1,
    title: 'Registration',
    start: '2026-08-07 14:00:00',
    end: '2026-08-07 16:00:00',
    resourceId: 'entrance',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Entrance',
    },
  },
  {
    id: 2,
    title: 'Registration',
    start: '2026-08-07 14:00:00',
    end: '2026-08-07 16:00:00',
    resourceId: 'reception',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Reception',
    },
  },
  {
    id: 3,
    title: 'Braai Social',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'bar',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Bar',
    },
  },
  {
    id: 4,
    title: 'Drinks / Socials',
    start: '2026-08-07 19:00:00',
    end: '2026-08-07 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Bar',
    },
  },
  {
    id: 5,
    title: 'Braai Social',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'resturant',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Restaurant',
    },
  },
  {
    id: 6,
    title: 'Braai Social',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'pool',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Pool',
    },
  },
  {
    id: 7,
    title: 'Mystery Game',
    start: '2026-08-07 18:30:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 8,
    title: 'Opening Ceremonies',
    start: '2026-08-07 19:00:00',
    end: '2026-08-07 20:30:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
      description:
        'Join us for the opening ceremonies, where we kick off the convention with excitement and anticipation.',
    },
  },
  {
    id: 9,
    title: 'Karaoke',
    start: '2026-08-07 20:30:00',
    end: '2026-08-07 22:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Friday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 10,
    title: 'AD Games',
    start: '2026-08-07 22:00:00',
    end: '2026-08-07 23:59:59',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Friday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 11,
    title: 'Fursuiting Availability',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Kraal',
    },
  },
  {
    id: 12,
    title: 'Fursuiting Availability',
    start: '2026-08-07 20:30:00',
    end: '2026-08-08 01:00:00',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Kraal',
    },
  },
  {
    id: 13,
    title: 'Dealers Den',
    start: '2026-08-07 16:00:00',
    end: '2026-08-07 19:00:00',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: false,
      day: 'Friday',
      room: 'Nyathi',
    },
  },
  {
    id: 14,
    title: 'Mystery Game',
    start: '2026-08-07 20:30:00',
    end: '2026-08-07 21:00:00',
    resourceId: 'nyathi',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Friday',
      room: 'Nyathi',
    },
  },
  {
    id: 15,
    title: 'Dealers Den AD',
    start: '2026-08-07 21:00:00',
    end: '2026-08-07 23:59:59',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: true,
      day: 'Friday',
      room: 'Nyathi',
    },
  },
  {
    id: 16,
    title: 'Fursuiting Photo Op',
    start: '2026-08-07 20:30:00',
    end: '2026-08-07 23:00:00',
    resourceId: 'gym',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Friday',
      room: 'Gym',
    },
  },
  {
    id: 17,
    title: 'Drinks / Socials',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Bar',
    },
  },
  {
    id: 18,
    title: 'Admin Brunch',
    start: '2026-08-08 09:00:00',
    end: '2026-08-08 10:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 19,
    title: 'Brunch',
    start: '2026-08-08 10:00:00',
    end: '2026-08-08 11:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 20,
    title: 'Admin Linner',
    start: '2026-08-08 16:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 21,
    title: 'Linner',
    start: '2026-08-08 17:00:00',
    end: '2026-08-08 18:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Saturday',
      room: 'Restaurant',
    },
  },
  {
    id: 22,
    title: 'Social & Gathering',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 18:00:00',
    resourceId: 'pool',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Pool',
    },
  },
  {
    id: 23,
    title: 'Mystery Game',
    start: '2026-08-08 08:30:00',
    end: '2026-08-08 09:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 24,
    title: 'Paws To The Beat',
    start: '2026-08-08 09:00:00',
    end: '2026-08-08 10:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Kyuki',
    },
  },
  {
    id: 25,
    title: 'Funger Games',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 12:00:00',
    resourceId: 'shumba-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 26,
    title: 'Mystery Game',
    start: '2026-08-08 12:00:00',
    end: '2026-08-08 12:30:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 27,
    title: 'Life After Animation: From Industry Veteran to Avatar Creator',
    start: '2026-08-08 12:30:00',
    end: '2026-08-08 14:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Bowie',
    },
  },
  {
    id: 28,
    title: 'Furry Feud',
    start: '2026-08-08 16:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Shumba Hall',
      host: 'Raging Snep',
    },
  },
  {
    id: 29,
    title: 'Pup-Play Photos',
    start: '2026-08-08 23:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Saturday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 30,
    title: 'Blood On The Clocktower',
    start: '2026-08-08 14:00:00',
    end: '2026-08-08 16:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Boardroom',
      host: 'ARKA',
    },
  },
  {
    id: 31,
    title: 'Blood On The Clocktower',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 20:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Boardroom',
      host: 'ARKA',
    },
  },
  {
    id: 32,
    title: 'Intro to Impact Play',
    start: '2026-08-08 23:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Saturday',
      room: 'Small Boardroom',
      host: 'Rigel Badger',
    },
  },
  {
    id: 33,
    title: 'The Switch Switch',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 19:00:00',
    resourceId: 'small-office',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Office',
      host: 'Sudan Red',
    },
  },
  {
    id: 34,
    title: 'Mystery Game',
    start: '2026-08-08 19:00:00',
    end: '2026-08-08 19:30:00',
    resourceId: 'small-office',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Small Office',
    },
  },
  {
    id: 35,
    title: 'Fursuit 101',
    start: '2026-08-08 14:00:00',
    end: '2026-08-08 15:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 36,
    title: 'Fursuit Games',
    start: '2026-08-08 15:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 37,
    title: 'Rave',
    start: '2026-08-08 18:00:00',
    end: '2026-08-08 23:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Saturday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 38,
    title: 'Fursuiting Availability',
    start: '2026-08-08 09:00:00',
    end: '2026-08-09 01:00:00',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Saturday',
      room: 'Kraal',
    },
  },
  {
    id: 39,
    title: 'Dealers Den',
    start: '2026-08-08 11:00:00',
    end: '2026-08-08 17:00:00',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: false,
      day: 'Saturday',
      room: 'Nyathi',
    },
  },
  {
    id: 40,
    title: 'Dealers Den AD',
    start: '2026-08-08 20:00:00',
    end: '2026-08-08 23:59:59',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: true,
      day: 'Saturday',
      room: 'Nyathi',
    },
  },
  {
    id: 41,
    title: 'Drinks / Socials',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 23:00:00',
    resourceId: 'bar',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Bar',
    },
  },
  {
    id: 42,
    title: 'Admin Brunch',
    start: '2026-08-09 09:00:00',
    end: '2026-08-09 10:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 43,
    title: 'Brunch',
    start: '2026-08-09 10:00:00',
    end: '2026-08-09 11:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 44,
    title: 'Admin Linner',
    start: '2026-08-09 16:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 45,
    title: 'Linner',
    start: '2026-08-09 17:00:00',
    end: '2026-08-09 18:00:00',
    resourceId: 'resturant',
    color: 'yellow',
    payload: {
      category: 'Meals',
      adult: false,
      day: 'Sunday',
      room: 'Restaurant',
    },
  },
  {
    id: 46,
    title: 'Social & Gathering',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 18:00:00',
    resourceId: 'pool',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Pool',
    },
  },
  {
    id: 47,
    title: 'Mystery Game',
    start: '2026-08-09 08:30:00',
    end: '2026-08-09 09:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 48,
    title: 'Paws To The Beat',
    start: '2026-08-09 09:00:00',
    end: '2026-08-09 10:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      host: 'Kyuki',
    },
  },
  {
    id: 49,
    title: "The Hybrid's Hybrid Art Challenge",
    start: '2026-08-09 15:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
      host: 'Judee',
    },
  },
  {
    id: 50,
    title: 'Movies',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:59:59',
    resourceId: 'shumba-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Shumba Hall',
    },
  },
  {
    id: 51,
    title: 'Business & Taxes',
    start: '2026-08-09 11:00:00',
    end: '2026-08-09 12:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Kiyo/Yote',
    },
  },
  {
    id: 52,
    title: 'Furry Business 101',
    start: '2026-08-09 12:00:00',
    end: '2026-08-09 13:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Blueberry',
    },
  },
  {
    id: 53,
    title: 'The South-African IT Landscape For Students & Jobseekers',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 14:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'CheddarByte',
    },
  },
  {
    id: 54,
    title: 'Content Creation',
    start: '2026-08-09 14:00:00',
    end: '2026-08-09 14:30:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Sefu',
    },
  },
  {
    id: 55,
    title: 'So You Want To Run A Furry Con',
    start: '2026-08-09 14:30:00',
    end: '2026-08-09 15:00:00',
    resourceId: 'small-boardroom',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Small Boardroom',
      host: 'Scratch, Jack, Kiyo/Yote',
    },
  },
  {
    id: 56,
    title: 'Mystery Game',
    start: '2026-08-09 12:30:00',
    end: '2026-08-09 13:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 57,
    title: 'Fursuit Games',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 15:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 58,
    title: 'Sudan Death (Quizz)',
    start: '2026-08-09 15:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'tlou-hall',
    color: 'orange',
    payload: {
      category: 'Featured',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Sudan Red',
    },
  },
  {
    id: 59,
    title: 'SAFC Dance Competition',
    start: '2026-08-09 18:00:00',
    end: '2026-08-09 20:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 60,
    title: 'Raffle',
    start: '2026-08-09 20:00:00',
    end: '2026-08-09 21:00:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 61,
    title: 'Closing Ceremonies',
    start: '2026-08-09 21:00:00',
    end: '2026-08-09 22:00:00',
    resourceId: 'tlou-hall',
    color: 'grape',
    payload: {
      category: 'Headline',
      adult: false,
      day: 'Sunday',
      room: 'Tlou Hall',
    },
  },
  {
    id: 62,
    title: 'Spice Is Right Game',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:00:00',
    resourceId: 'tlou-hall',
    color: 'blue',
    payload: {
      category: 'Panel / Activity',
      adult: true,
      day: 'Sunday',
      room: 'Tlou Hall',
      host: 'Raging Snep',
    },
  },
  {
    id: 63,
    title: 'Fursuiting Availability',
    start: '2026-08-09 09:00:00',
    end: '2026-08-10 01:00:00',
    resourceId: 'kraal',
    color: 'teal',
    payload: {
      category: 'Drop-in',
      adult: false,
      day: 'Sunday',
      room: 'Kraal',
    },
  },
  {
    id: 64,
    title: 'Dealers Den',
    start: '2026-08-09 13:00:00',
    end: '2026-08-09 17:00:00',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: false,
      day: 'Sunday',
      room: 'Nyathi',
    },
  },
  {
    id: 65,
    title: 'Dealers Den AD',
    start: '2026-08-09 22:00:00',
    end: '2026-08-09 23:59:59',
    resourceId: 'nyathi',
    color: 'green',
    payload: {
      category: 'Dealers / Sales',
      adult: true,
      day: 'Sunday',
      room: 'Nyathi',
    },
  },
];
